### ISSUE TITLE
yolov5-Paddle🚀重大更新😎😎

### ISSUE THREAD

**Issue by GuoQuanhao** [GuoQuanhao/yolov5-Paddle#16]
本次更新实现了yolov5 v7.0的全新迁移，能够实现分类、分割、检测和各种格式模型的导出。
&#9745; 多卡训练
&#9745; 指定单卡训练和CPU训练
&#9745; TensorRT
&#9745; ONNX
&#9745; OpenVIVO
&#9745; PaddleInference
&#9745; PaddleLite
&#9745; 断点续训
&#9745; 自动下载模型
&#9745; 自动下载数据集
&#9745; 解决NMS过慢问题
&#9745; 解决显存占用过高问题
&#9745; benchmark
```
python benchmarks.py --weights ./yolov5s.pdparams --device 0
```
```
Benchmarks complete (187.81s)
            Format  Size (MB)  mAP50-95  Inference time (ms)
0     PaddlePaddle       13.9    0.4716                 9.75
1  PaddleInference       27.8    0.4716                20.82
2             ONNX       27.6    0.4717                32.23
3         TensorRT       32.2    0.4717                 3.05
4         OpenVINO       27.9    0.4717                43.67
5       PaddleLite       27.8    0.4717               264.86
```

**Comment by Grubby-Wang** [comment]
我的目的是：导出可用于c++推理的模型，采用官方提供的paddle_yolo训练导出的模型，格式包含以下几个文件：
```
infer_cfg.yml
model.pdiparams
model.pdmodel
model.pdiparams.info
```
按新的版本进行了" PaddleInference"导出，如下：
`!python export.py --data ./data/personnal_data.yaml --weights yolov5l.pdparams --device 0 --include paddleinfer `

导出的模型仅有后面三个文件，不包含“infer_cfg.yml”，因此导致c++推理中，初始化会出现问题。
实际的“infer_cfg.yml”包含以下内容：
```
mode: paddle
draw_threshold: 0.5
metric: VOC
use_dynamic_shape: false
arch: YOLOv5
min_subgraph_size: 20
Preprocess:
- interp: 1
  keep_ratio: true
  target_size:
  - 640
  - 640
  type: Resize
- fill_value:
  - 114.0
  - 114.0
  - 114.0
  size:
  - 640
  - 640
  type: Pad
- type: Permute
label_list:
- x
- y
- z
```

是本人export中用法不对么？还是其他原因？希望解答，谢谢
