### ISSUE TITLE
paddleinference用于c++推理问题

### ISSUE THREAD

**Issue by Grubby-Wang** [GuoQuanhao/YOLOv5-Paddle#18]
我的目的是：导出可用于c++推理的模型，采用官方提供的paddle_yolo训练导出的模型，格式包含以下几个文件：
```
infer_cfg.yml
model.pdiparams
model.pdmodel
model.pdiparams.info
```
按新的版本进行了" PaddleInference"导出，如下：
`!python export.py --data ./data/personnal_data.yaml --weights yolov5l.pdparams --device 0 --include paddleinfer `

导出的模型仅有后面三个文件，不包含“infer_cfg.yml”，因此导致c++推理中，初始化会出现问题。
实际的“infer_cfg.yml”包含以下内容：
```
mode: paddle
draw_threshold: 0.5
metric: VOC
use_dynamic_shape: false
arch: YOLOv5
min_subgraph_size: 20
Preprocess:
- interp: 1
  keep_ratio: true
  target_size:
  - 640
  - 640
  type: Resize
- fill_value:
  - 114.0
  - 114.0
  - 114.0
  size:
  - 640
  - 640
  type: Pad
- type: Permute
label_list:
- x
- y
- z
```

是本人export中用法不对么？还是其他原因？希望解答，谢谢
